In [6]:
import numpy as np  # Import NumPy library for numerical operations

# Create a random number generator object with a fixed seed for reproducibility
rand = np.random.RandomState(42)

# Generate a 1D array of 10 random integers between 0 and 99
x = rand.randint(100, size=10)
print("Original array:", x)
# Example Output: [51 92 14 71 60 20 82 86 74 74]

# ----------------------------------------
# Basic Fancy Indexing on 1D Array
# ----------------------------------------

# Traditional way of accessing multiple elements manually
print("Access individually:", [x[3], x[7], x[2]])  # Output: [71, 86, 14]

# Fancy indexing allows you to pass a list of indices to get multiple values at once
ind = [3, 7, 4]
print("Fancy indexing with list:", x[ind])  # Output: [71 86 60]

# You can use multi-dimensional arrays as indices too
ind2d = np.array([[3, 7],
                  [4, 5]])  # 2x2 array of indices
print("Fancy indexing with 2D array:\n", x[ind2d])
# Output:
# [[71 86]
#  [60 20]]

# ----------------------------------------
# Fancy Indexing in 2D Arrays
# ----------------------------------------

# Create a 2D array with shape (3 rows x 4 columns)
X = np.arange(12).reshape((3, 4))
print("2D Array X:\n", X)
# Output:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Create arrays for rows and columns we want to index
row = np.array([0, 1, 2])  # Row indices: 0th, 1st, 2nd row
col = np.array([2, 1, 3])  # Column indices: 2nd, 1st, 3rd column

# This pairs (0,2), (1,1), and (2,3)
print("Fancy indexing in 2D:", X[row, col])  # Output: [2 5 11]

# ----------------------------------------
# Broadcasting in Fancy Indexing
# ----------------------------------------
print("reshaping row to col",row[:, np.newaxis]) # Reshape row to a column vector
# Reshape row to be a column vector using np.newaxis
# This will broadcast with the 'col' array to form all combinations
# shape of row[:, np.newaxis] is (3, 1), col is (3,)
broadcasted_result = X[row[:, np.newaxis], col]
print("Broadcasted fancy indexing result:\n", broadcasted_result)
# Output:
# [[ 2  1  3]
#  [ 6  5  7]
#  [10  9 11]]

# Broadcasting is similar to cross-multiplying each row index with all column indices
# We perform element-wise multiplication of 'row' (reshaped to column vector) with 'col' (row vector)
print("Broadcasted multiplication:", row[:, np.newaxis] * col)
# Explanation:
# row[:, np.newaxis] reshapes 'row' from shape (3,) to (3,1)
# col has shape (3,)
# Broadcasting rules expand these to shape (3,3) for multiplication
# Each row index multiplies with every column index, resulting in a 3x3 matrix:
# [[0*2, 0*1, 0*3],
#  [1*2, 1*1, 1*3],
#  [2*2, 2*1, 2*3]] = [[0,0,0],[2,1,3],[4,2,6]]

# ----------------------------------------
# Combining Fancy Indexing with Other Indexing Techniques
# ----------------------------------------

# Mixing simple index (single integer) and fancy indexing (list of indices)
# X[2, [2, 0, 1]] means:
# - Fix row index at 2 (third row)
# - Pick columns at indices 2, 0, and 1 (third, first, second columns)
# So it fetches elements: X[2,2], X[2,0], X[2,1] = 10, 8, 9
print("Mixed simple and fancy indexing:", X[2, [2, 0, 1]])

# Mixing slicing and fancy indexing
# X[1:, [2, 0, 1]] means:
# - Slice rows starting from index 1 (second row to end)
# - Pick columns at indices 2, 0, 1 for each sliced row
# It returns a 2D array with shape (2,3) since rows=2 (index 1 and 2), columns=3 (2,0,1)
# Elements fetched:
# Row 1: X[1,2], X[1,0], X[1,1] = 6, 4, 5
# Row 2: X[2,2], X[2,0], X[2,1] = 10, 8, 9
print("Fancy indexing with slicing:\n", X[1:, [2, 0, 1]])

# Combining fancy indexing with boolean masking
mask = np.array([1, 0, 1, 0], dtype=bool) #creates a boolean mask for columns
# True means select that column, False means ignore
# Here, columns at index 0 and 2 are True, so we select those columns

# X[row[:, np.newaxis], mask]:
# - row[:, np.newaxis] reshapes row indices to (3,1) for broadcasting
# - mask is applied along the columns, selecting only True columns (0th and 2nd)
# So for each row in 'row' array (0,1,2), we get elements from columns 0 and 2
# Elements fetched:
# Row 0: X[0,0], X[0,2] = 0, 2
# Row 1: X[1,0], X[1,2] = 4, 6
# Row 2: X[2,0], X[2,2] = 8, 10
print("Fancy indexing with mask:\n", X[row[:, np.newaxis], mask])


Original array: [51 92 14 71 60 20 82 86 74 74]
Access individually: [np.int32(71), np.int32(86), np.int32(14)]
Fancy indexing with list: [71 86 60]
Fancy indexing with 2D array:
 [[71 86]
 [60 20]]
2D Array X:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Fancy indexing in 2D: [ 2  5 11]
reshaping row to col [[0]
 [1]
 [2]]
Broadcasted fancy indexing result:
 [[ 2  1  3]
 [ 6  5  7]
 [10  9 11]]
Broadcasted multiplication: [[0 0 0]
 [2 1 3]
 [4 2 6]]
Mixed simple and fancy indexing: [10  8  9]
Fancy indexing with slicing:
 [[ 6  4  5]
 [10  8  9]]
Fancy indexing with mask:
 [[ 0  2]
 [ 4  6]
 [ 8 10]]
