In [24]:
import numpy as np # import library

#making a python list as numpy array
my_list = [1, 2, 3, 4, 5]
array= np.array(my_list) # converting list to numpy array
print(type(array)) # getting the type of the array

arr = np.array([10, 20, 30, 40, 50]) #Creates a numpy array
print(arr) # Prints the numpy array

<class 'numpy.ndarray'>
[10 20 30 40 50]


In [18]:
list1 = [1, 2, 3, 4, 5] # Creates a list
list2 = [6, 7, 8, 9, 10] # Creates another list
list3 = [11, 12, 13, 14, 15] # Creates a third list


#it opens with two square brackets and closes with two square brackets
twoDarray = np.array([list1, list2, list3]) # Creates a 2D numpy array from the lists
print(twoDarray) # Prints the 2D numpy array
print("shape of 2d array",twoDarray.shape) # Returns the shape of the 2D array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
shape of 2d array (3, 5)


In [ ]:
#indexing starts from 0
print("value of 3rd index in 1D array is", array[3])#it was 4 but after changin index it changes

#we can also change the value of an index
array[3] = 10 # Changes the value at index 3 to 10
print("value of 3rd index in 1D array after change is", array[3]) # Prints the changed value


#if we want to see range then we can use colons
print("value of 2nd to 4th index in 1D array is", array[1:4]) # Prints the values from index 1 to 3 (4 is excluded) 0th is 1, 1st is 2, 2nd is 3, 3rd is 4 , 4th is 5

#we can also use negative indexing
print("value of 2nd to 4th index in 1D array using negative indexing is", array[-4:-1]) # Prints the values from index -4 to -2 (-1 is excluded) -1st is 5, -2nd is 4, -3rd is 3, -4th is 2, -5th is 1

#multi-dimensional indexing
print("only print 1st col of 2D array, index start from 0 and we are printing 1st col", twoDarray[:, 1]) # Prints the first column of the 2D array

#now accesing 0th col of 2D array 
print("only print 0th col of 2D array, index start from 0 and we are printing 0th col", twoDarray[:, 0]) # Prints the first column of the 2D array

#suppose we want to print 3 4 and 4 5 from 1st and 2nd row so 
print('printing 7 8 12 13 of 2D array', twoDarray[1:,1:3])
print('printing 9 10 14 15 of 2D array', twoDarray[1:,3:])

value of 3rd index in 1D array is 10
value of 3rd index in 1D array after change is 10
value of 2nd to 4th index in 1D array is [ 2  3 10]
value of 2nd to 4th index in 1D array using negative indexing is [ 2  3 10]
only print 1st col of 2D array, index start from 0 and we are printing 1st col [ 2  7 12]
only print 0th col of 2D array, index start from 0 and we are printing 0th col [ 1  6 11]
printing 7 8 12 13 [[ 7  8]
 [12 13]]
printing 9 10 14 15 [[ 9 10]
 [14 15]]


In [ ]:
#Reshape of 2D array
reshaped_array = twoDarray.reshape(5, 3) # Reshapes the 2D array to a new shape (5 rows, 3 columns)
print("reshaped array", reshaped_array) # Prints the reshaped array

# important while reshaping is while reshaping the number of elements should be same
# for example if we have 15 elements in 2D array then we can reshape it to 3x5 or 5x3 but not to 4x4 or 2x7

reshaped array [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
#arrange function 
arrangedArray = np.arange(1, 21, 2) # Creates an array with values from 1 to 20 with a step of 2, (initial value, final value, step)
print("arranged array with step of 2", arrangedArray) # Prints the arranged array

#reshaping arranged array
reshapingArrangedArray = np.arange(1,20,2).reshape(5, 2) # Reshapes the arranged array to a new shape (5 rows, 2 columns)
print("reshaped arranged array", reshapingArrangedArray) # Prints the reshaped arranged array

#creating a 3D array by using arrange and reshape
threeDarray = np.arange(1, 28).reshape(3, 3, 3) # Creates a 3D array with values from 1 to 27 and reshapes it to (3, 3, 3)
print("3D array", threeDarray) # Prints the 3D array
# 3D array consists of number of 2D arrays, in this case 3 2D arrays

arranged array with step of 2 [ 1  3  5  7  9 11 13 15 17 19]
reshaped arranged array [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]
3D array [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
#you can also do multiple operations on numpy arrays like addition, subtraction, multiplication, division etc.
#for example
print("2D array multiplied by 2", twoDarray * 2) # Prints the 2D array multiplied by 2

#another function is .ones() which creates an array of ones
ones_array = np.ones((3, 3)) # Creates a 3x3 array of ones
print("3x3 array of ones", ones_array) # Prints the 3x3 array of ones // similarly we can use .zeros() to create an array of zeros

#another function is .eye() which creates an identity matrix
identity_matrix = np.eye(3) # Creates a 3x3 identity matrix
print("3x3 identity matrix", identity_matrix) # Prints the 3x3 identity matrix

# There are many more functions in numpy like .sum(), .mean(), .max(), .min() etc.
# As per your requirement you can use these functions to perform various operations on numpy arrays



2D array multiplied by 2 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
3x3 array of ones [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3x3 identity matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
#Let us learn about NaN np.nan and when we use it, how we use it and what is the use of it
# NaN stands for Not a Number, it is used to represent missing or undefined values in numpy arrays
nan_array = np.array([1, 2, np.nan, 4, 5]) # Creates a numpy array with NaN value
print("Numpy array with NaN value", nan_array) # Prints the numpy array with NaN value

# suppose we are getting data from exel or csv file and some values are missing then we can use NaN to represent those missing values
# we can check if the value is NaN or not using np.isnan() function
#suppose excel file has data of height of students but  height of 4th student and 7th student is missing then we can represent it as NaN
# .isnan, when u get data or an array and you want to check if number is missing or it is a string instead of number then you can use this function


Numpy array with NaN value [ 1.  2. nan  4.  5.]


# This is how you  can use isnan while dealing with real problem, you can check EXCELL sheet present 
# We read the Excel data (skipping the header) into a NumPy array with mixed types, replaced missing numeric values (None) with np.nan for proper handling, extracted numeric columns using array slicing, converted them to floats, and then calculated the mean while ignoring the missing values using np.nanmean(). This approach efficiently handles large datasets and missing data for numerical analysis.

In [50]:
from openpyxl import load_workbook

# Step 1: Load the Excel workbook and select the active worksheet
wb = load_workbook('Marks.xlsx')
ws = wb.active  # or ws = wb['Sheet1']

print("Worksheet title:", ws.title)

# Step 2: Read all data rows (skip header at row 1)
data = []
for row in ws.iter_rows(min_row=2, values_only=True):
    data.append(list(row))

print(f"Number of data rows read: {len(data)}")
# Avoid printing all raw data if it's large

# Step 3: Convert list of rows to a NumPy array with dtype=object 
# dtype=object is used to handle mixed types (strings, floats, None)
arr = np.array(data, dtype=object)
print("Array shape:", arr.shape)

if arr.size == 0:
    print("No data to process")
else:
    # Step 4: Extract the 'Marks' column (index 1) and 'Age' column (index 2) using NumPy slicing
    # arr[:, 1] means: all rows, column at index 1 (Marks)
    # arr[:, 2] means: all rows, column at index 2 (Age)
    marks_col = arr[:, 1]
    age_col = arr[:, 2]

    # Step 5: Replace None values with np.nan (missing numeric data)
    # np.where(condition, value_if_true, value_if_false) is vectorized and efficient
    marks_col = np.where(marks_col == None, np.nan, marks_col)
    age_col = np.where(age_col == None, np.nan, age_col)

    # Step 6: Put the cleaned columns back into the original array
    arr[:, 1] = marks_col
    arr[:, 2] = age_col

    # Step 7: Convert these columns to float for numerical computations
    marks = arr[:, 1].astype(float)
    age = arr[:, 2].astype(float)

    # Step 8: Check for NaNs in the data (True where data is missing)
    print("NaN mask for Marks:", np.isnan(marks))
    print("NaN mask for Age:", np.isnan(age))

    # Step 9: Calculate mean ignoring NaN values using np.nanmean()
    mean_marks = np.nanmean(marks)
    mean_age = np.nanmean(age)

    print("Mean Marks (ignoring NaN):", mean_marks)
    print("Mean Age (ignoring NaN):", mean_age)


Worksheet title: Sheet1
Number of data rows read: 4
Array shape: (4, 3)
NaN mask for Marks: [False  True False False]
NaN mask for Age: [False False False  True]
Mean Marks (ignoring NaN): 80.0
Mean Age (ignoring NaN): 15.0


| Function       | NaN-safe Version   | Description                            |
|----------------|-------------------|------------------------------------|
| np.sum         | np.nansum         | Compute sum of elements             |
| np.prod        | np.nanprod        | Compute product of elements         |
| np.mean        | np.nanmean        | Compute mean of elements            |
| np.std         | np.nanstd         | Compute standard deviation          |
| np.var         | np.nanvar         | Compute variance                    |
| np.min         | np.nanmin         | Find minimum value                  |
| np.max         | np.nanmax         | Find maximum value                  |
| np.argmin      | np.nanargmin      | Find index of minimum value         |
| np.argmax      | np.nanargmax      | Find index of maximum value         |
| np.median      | np.nanmedian      | Compute median of elements          |
| np.percentile  | np.nanpercentile  | Compute rank-based statistics       |
| np.any         | N/A               | Evaluate whether any elements are true |
| np.all         | N/A               | Evaluate whether all elements are true |
