In [2]:
# NumPy Sorting and Partitioning Explained Simply
import numpy as np

# np.sort sorts an array and returns a new sorted array without changing the original.
x = np.array([2, 1, 4, 3, 5])
print("Sorted array using np.sort:", np.sort(x))  
# Output: [1 2 3 4 5]  # Sorted array returned, original x unchanged

# To sort the array in-place (change the original array), use the sort method of the array:
x.sort()
print("Array after in-place sort:", x)  
# Output: [1 2 3 4 5]  # Original array x is now sorted

# np.argsort returns the indices that would sort the array,
# not the sorted values themselves.
x = np.array([2, 1, 4, 3, 5])
indices = np.argsort(x)
print("Indices that would sort the array:", indices)  
# Output: [1 0 3 2 4]  
# Explanation: 
# indices[0] = 1 means the smallest element is at position 1 in x (which is 1)
# indices[1] = 0 means the second smallest element is at position 0 in x (which is 2), and so on.

# Using the indices from argsort with fancy indexing, you can get the sorted array:
print("Sorted array using fancy indexing with argsort indices:", x[indices])  
# Output: [1 2 3 4 5]

# Sorting along specific axis in multidimensional arrays:
rand = np.random.RandomState(42)  # Fixing random seed for reproducibility
X = rand.randint(0, 10, (4, 6))   # 4x6 matrix with random ints 0-9
print("Original 4x6 array:\n", X)

# Sort each column independently (axis=0 means sort vertically, down the rows)
print("Sorted each column (axis=0):\n", np.sort(X, axis=0))  
# Each column's values are sorted separately

# Sort each row independently (axis=1 means sort horizontally, across columns)
print("Sorted each row (axis=1):\n", np.sort(X, axis=1))  
# Each row's values are sorted separately

# Partial sorting: np.partition lets you find k smallest elements efficiently
x = np.array([7, 2, 3, 1, 6, 5, 4])
print("Array after np.partition with k=3:", np.partition(x, 3))  
# Output: [2 1 3 4 6 5 7]
# The first 3 elements are the smallest (not necessarily sorted), rest are after.

# Partitioning also works along an axis in multidimensional arrays:
print("Partitioned array along axis=1 with k=2:\n", np.partition(X, 2, axis=1))  
# For each row, the first 2 elements are the smallest of that row (unordered),
# rest fill the remaining slots.

# Summary:
# - np.sort returns a sorted copy, x.sort() sorts in-place.
# - np.argsort returns indices that sort the array.
# - axis argument lets you sort rows or columns separately.
# - np.partition efficiently finds the smallest k elements without full sorting.
# - np.argpartition returns indices of partition, like argsort for partition.


Sorted array using np.sort: [1 2 3 4 5]
Array after in-place sort: [1 2 3 4 5]
Indices that would sort the array: [1 0 3 2 4]
Sorted array using fancy indexing with argsort indices: [1 2 3 4 5]
Original 4x6 array:
 [[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]
Sorted each column (axis=0):
 [[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
Sorted each row (axis=1):
 [[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]
Array after np.partition with k=3: [1 2 3 4 5 6 7]
Partitioned array along axis=1 with k=2:
 [[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


In [10]:
import numpy as np

# ✅ What np.partition Does
# It is a fast way to find the smallest (or largest) k elements in an array.
# It does NOT fully sort the array.
# Instead:
# - The first k elements (along the specified axis) will be the k smallest values — unordered.
# - The remaining elements will be larger or equal.

# ✅ Example Array (2D)
X = np.array([
    [8, 2, 5, 1, 4, 9],
    [7, 3, 6, 4, 0, 5]
])

print("Original Array:\n", X)

# 🔹 np.partition(X, 2, axis=1)
# Means: "In each row, bring the 3 smallest elements to the front (0-based index = 2)"
# axis=1 → operate row-wise (across columns)
result_axis1 = np.partition(X, 2, axis=1)
print("\nPartitioned along axis=1 with k=2 (row-wise):\n", result_axis1)
# For each row, the smallest 3 values are moved to the first 3 positions
# within that row (not necessarily sorted among themselves).
# Example:
# Row [8, 2, 5, 1] becomes [2, 1, 5, 8] → 2, 1, 5 are the 3 smallest

# 🔹 np.partition(X, 1, axis=0)
# Means: "In each column, bring the 2 smallest elements to the top (0-based index = 1)"
# axis=0 → operate column-wise (down the rows)
result_axis0 = np.partition(X, 1, axis=0)
print("\nPartitioned along axis=0 with k=1 (column-wise):\n", result_axis0)
# Each column now has its two smallest values in the top two rows.

# ❌ axis=2 is invalid here
# X is a 2D array with shape (2, 4)
# axis=2 would mean you're trying to operate on a 3rd dimension, which doesn't exist
try:
    np.partition(X, 2, axis=2)
except np.AxisError as e:
    print("\n❌ Error with axis=2:", e)

# 📌 Summary in Simple Words:
# - np.partition is useful when you only need the smallest k values, not the full sorted array.
# - axis=1 → operate across rows (each row is handled separately)
# - axis=0 → operate down columns (each column is handled separately)
# - axis must be within the number of dimensions the array has:
#     - 1D array → only axis=0
#     - 2D array → axis=0 or axis=1
#     - 3D array → axis=0, 1, or 2

# 📌 Real-life Use Case:
# Suppose you want the top 3 fastest race times per athlete (row),
# you can use np.partition instead of full sorting, which saves time!


Original Array:
 [[8 2 5 1 4 9]
 [7 3 6 4 0 5]]

Partitioned along axis=1 with k=2 (row-wise):
 [[1 2 4 5 8 9]
 [0 3 4 5 6 7]]

Partitioned along axis=0 with k=1 (column-wise):
 [[7 2 5 1 0 5]
 [8 3 6 4 4 9]]


AttributeError: module 'numpy' has no attribute 'AxisError'